# Generated by Django 5.0.2 on 2025-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_eyereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('scanned', models.BooleanField(default=False)),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='eye_images/')),
            ],
        ),
        migrations.AddField(
            model_name='eyereport',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='eye_reports/'),
        ),
        migrations.AlterField(
            model_name='eyereport',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eyereport',
            name='disease',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eyereport',
            name='report_image',
            field=models.ImageField(default=1, upload_to='eye_images/'),
            preserve_default=False,
        ),
    ]
